services:
  fastapi_backend:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    networks:
      - web
    restart: always
    environment:
      - ENVIRONMENT=development

  react_frontend:
    build:
      context: ./React/aes-app
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - web
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/cloudflare_origin_cert.pem:/etc/nginx/certs/cloudflare_origin_cert.pem:ro
      - /etc/ssl/private/cloudflare_origin_key.pem:/etc/nginx/certs/cloudflare_origin_key.pem:ro
    depends_on:
      - fastapi_backend
      - react_frontend
    networks:
      - web

networks:
  web:
    driver: bridge