services:
  fastapi_backend:
    image: python:3.11-alpine
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    networks:
      - web
    restart: always
    working_dir: /usr/src/app
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./FastAPI:/usr/src/app
    command: >
      sh -c "
      apk add --no-cache gcc musl-dev &&
      pip install --no-cache-dir -r requirements.txt &&
      cd scripts && uvicorn api:server --host 0.0.0.0 --port 8000 --reload
      "

  react_frontend:
    image: node:lts-alpine
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - web
    restart: always
    working_dir: /usr/src/app
    command: >
      sh -c "
      npm ci --only=production &&
      npm start
      "
    volumes:
      - ./React/aes-app:/usr/src/app
      #- /usr/src/app/node_modules

  nginx_http:
    image: nginx:alpine-slim
    container_name: nginx_http
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-http.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi_backend
      - react_frontend
    networks:
      - web
    profiles:
      - http

  nginx_selfsign:
    image: nginx:alpine-slim
    container_name: nginx_selfsign
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx-selfsign.conf:/etc/nginx/nginx.conf:ro
    entrypoint: >
      sh -c "
      apk add --no-cache openssl &&
      mkdir -p /etc/nginx/certs &&
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/selfsigned.key -out /etc/nginx/certs/selfsigned.crt -subj '/C=US/ST=State/L=City/O=Organization/OU=OrgUnit/CN=localhost' &&
      nginx -g 'daemon off;'
      "
    depends_on:
      - fastapi_backend
      - react_frontend
    networks:
      - web
    profiles:
      - dev

  nginx_prod:
    image: nginx:alpine-slim
    container_name: nginx-prod
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      # make sure to modify path to cert and private key here
      - /etc/ssl/certs/cloudflare_origin_cert.pem:/etc/nginx/certs/cloudflare_origin_cert.pem:ro 
      - /etc/ssl/private/cloudflare_origin_key.pem:/etc/nginx/certs/cloudflare_origin_key.pem:ro
    depends_on:
      - fastapi_backend
      - react_frontend
    networks:
      - web
    profiles:
      - production

networks:
  web:
    driver: bridge