services:
  fastapi_backend:
    image: python:3.11-alpine
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    networks:
      - web
    restart: always
    working_dir: /usr/src/app
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./FastAPI:/usr/src/app
    command: >
      sh -c "
      apk add --no-cache gcc musl-dev &&
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn api:server --host 0.0.0.0 --port 8000
      "

  react_frontend:
    image: node:lts-alpine
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - web
    restart: always
    working_dir: /usr/src/app
    command: >
      sh -c "
      npm ci --only=production &&
      npm start
      "
    volumes:
      - ./React/aes-app:/usr/src/app

  nginx_dev:
    image: nginx:alpine-slim
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi_backend
      - react_frontend
    networks:
      - web
    profiles:
      - dev

  nginx_prod:
    image: nginx:alpine-slim
    container_name: nginx-prod
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      # make sure to modify path to cert and private key here
      - /etc/ssl/certs/cloudflare_origin_cert.pem:/etc/nginx/certs/cloudflare_origin_cert.pem:ro 
      - /etc/ssl/private/cloudflare_origin_key.pem:/etc/nginx/certs/cloudflare_origin_key.pem:ro
    depends_on:
      - fastapi_backend
      - react_frontend
    networks:
      - web
    profiles:
      - production

networks:
  web:
    driver: bridge